"""
ActionRecommendation and ActionReview models.

excursion → action_recommendations → action_reviews

HUMAN APPROVAL BOUNDARY:
No automated action is ever taken.  An engineer must explicitly approve/reject/defer
every recommendation via the Actions screen.  All decisions are written to action_reviews
for a complete audit trail.
"""
from datetime import datetime, timezone

from sqlalchemy import DateTime, ForeignKey, Integer, String, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database import Base


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class ActionRecommendation(Base):
    """
    A corrective-action recommendation generated by the analytics pipeline
    for a given excursion.

    priority: 'high' | 'medium' | 'low'
    All recommendations start as advisory — no action is taken automatically.
    """

    __tablename__ = "action_recommendations"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    excursion_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("excursions.id", ondelete="CASCADE"), nullable=False, index=True
    )
    action_text: Mapped[str] = mapped_column(Text, nullable=False)
    priority: Mapped[str] = mapped_column(String(16), nullable=False, default="medium", index=True)
    produced_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )

    # Relationships
    excursion: Mapped["Excursion"] = relationship(  # type: ignore[name-defined]
        "Excursion", back_populates="action_recommendations"
    )
    reviews: Mapped[list["ActionReview"]] = relationship(
        "ActionReview", back_populates="recommendation", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:
        return (
            f"<ActionRecommendation id={self.id} excursion_id={self.excursion_id} "
            f"priority={self.priority!r}>"
        )


class ActionReview(Base):
    """
    Engineer's decision on an action recommendation.

    decision: 'approve' | 'reject' | 'defer'
    This table is the audit trail — every review is immutable once written.
    engineer_id is stored as a plain string (no auth in v1 prototype).
    """

    __tablename__ = "action_reviews"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    recommendation_id: Mapped[int] = mapped_column(
        Integer,
        ForeignKey("action_recommendations.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    engineer_id: Mapped[str] = mapped_column(String(64), nullable=False, index=True)
    decision: Mapped[str] = mapped_column(String(16), nullable=False, index=True)
    rationale: Mapped[str | None] = mapped_column(Text, nullable=True)
    reviewed_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, index=True
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )

    # Relationships
    recommendation: Mapped["ActionRecommendation"] = relationship(
        "ActionRecommendation", back_populates="reviews"
    )

    def __repr__(self) -> str:
        return (
            f"<ActionReview id={self.id} recommendation_id={self.recommendation_id} "
            f"engineer={self.engineer_id!r} decision={self.decision!r}>"
        )
