"""
RootCauseRanking model.

excursion → root_cause_rankings (top-3 evidence-based root cause candidates)

IMPORTANT: root causes are NEVER generated by an LLM.
They are produced by the deterministic evidence-fusion service (Sub-Task 4d).
This table stores the frozen output of that analysis.
"""
from datetime import datetime, timezone

from sqlalchemy import DateTime, Float, ForeignKey, Integer, String
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.models._types import JsonColumn

from app.database import Base


def _utcnow() -> datetime:
    return datetime.now(timezone.utc)


class RootCauseRanking(Base):
    """
    One root-cause candidate in a ranked list for an excursion.

    rank: 1 = top candidate, 2 = second, 3 = third.
    score: normalised [0,1] weighted evidence score.
    confidence: separation ratio = 1 - (score_2 / score_1) for rank-1; 0 for others.
    evidence_ids: JSONB list of evidence item IDs that contributed.
    supporting_signals: JSONB dict of signals that support this cause.
    contradicting_signals: JSONB dict of signals that argue against this cause.
    model_name / model_version: identifies the evidence-fusion algorithm version.
    produced_at: timestamp when the analysis was run (audit).
    """

    __tablename__ = "root_cause_rankings"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    # excursion_id nullable — allows stand-alone analysis without a linked excursion
    excursion_id: Mapped[int | None] = mapped_column(
        Integer, ForeignKey("excursions.id", ondelete="CASCADE"), nullable=True, index=True
    )
    rank: Mapped[int] = mapped_column(Integer, nullable=False)
    cause: Mapped[str] = mapped_column(String(128), nullable=False, index=True)
    score: Mapped[float] = mapped_column(Float, nullable=False)
    confidence: Mapped[float] = mapped_column(Float, nullable=False)
    evidence_ids: Mapped[list] = mapped_column(JsonColumn, nullable=False, default=list)
    supporting_signals: Mapped[dict] = mapped_column(JsonColumn, nullable=False, default=dict)
    contradicting_signals: Mapped[dict] = mapped_column(JsonColumn, nullable=False, default=dict)
    model_name: Mapped[str] = mapped_column(String(64), nullable=False)
    model_version: Mapped[str] = mapped_column(String(32), nullable=False)
    produced_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, index=True
    )

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, default=_utcnow, onupdate=_utcnow
    )

    # Relationships
    excursion: Mapped["Excursion | None"] = relationship(  # type: ignore[name-defined]
        "Excursion", back_populates="root_cause_rankings"
    )

    def __repr__(self) -> str:
        return (
            f"<RootCauseRanking id={self.id} excursion_id={self.excursion_id} "
            f"rank={self.rank} cause={self.cause!r} score={self.score:.3f}>"
        )
